### PR TITLE
Cleanup and raise iOS deployment target

### PR DESCRIPTION
**Pull request by suhailskhan**
General cleanup, including removal of now-unused (?) CocoaPods files, and moving of a source file into proper directory.

Additionally, when building the project, Xcode automatically modified the `Package.resolved` file. Said modifications have been committed.

I raised the deployment target to iOS 15 (and watchOS 8). This would serve to benefit several aspects of the codebase, including removing the need for UIKit backwards compatibility for iOS 12, enabling us to migrate the Apple Watch app from WatchKit to full SwiftUI, removing the need for all of the `@available` and `if #available` statements, and allowing us to take greater advantage of features from SwiftUI 3 and above. However, it should be noted that an iOS 13 or 14 target may also suffice. The best choice will depend on data from the App Store regarding distribution of iOS releases among this app’s user base.

Lastly, I have changed the project format to Xcode 14 as this is the default format when creating new iOS app projects in Xcode 15.0; it is generally a good practice to keep the project format up-to-date.

Cc @oalejel

### CODE REVIEW

**Comment by oalejel** [comment]
Amazing, JAK.

lemme take a look sometime this weekend iA to get this merged with what I have locally. I’m also planning on supporting the new StandBy widget view iA.

**Comment by suhailskhan** [comment]
> lemme take a look sometime this weekend iA to get this merged with what I have locally.

If it's all the same to you, you can instead just continue working to push what you have locally to `master` and I then I will rebase my `cleanup` branch from the updated `master`. I can handle any conflicts from the rebase, should they occur, and then the PR would be ready from there. Just thought that might be more convenient, but I might be wrong. Either way is fine by me.

> I’m also planning on supporting the new StandBy widget view iA.

Exciting to hear!

**Review by oalejel — APPROVED** [review]
Changes LGTM; merging. Will be pushing a few new features to master after testing iA.

**Comment by suhailskhan** [comment]
Heads up, although you probably already saw this from the CI test results. I had forgotten to also raise the deployment target for the Watch Extension to watchOS 8.

**Pull request merged**
